# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GNSInternalTools' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GNSInternalTools
  pod 'gRPC-Swift', '~> 1.0.0'
  pod 'gRPC-Swift-Plugins'
  target 'GNSInternalToolsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GNSInternalToolsUITests' do
    # Pods for testing
  end

end
